### ISSUE TITLE
硬件转发可用吗?

### ISSUE THREAD

**Issue by ALILEX-1** [932521665/openwrt-myLede-redmi-ax60000#1]

**Comment by momoc-ani** [comment]
应该是可以，可能编译的依赖问题？系统已经崩了，重新救会官网了。

**Comment by momoc-ani** [comment]
网速没啥区别，我300兆都基本能跑满。

**Comment by ALILEX-1** [comment]
硬件分区没改可以官网救砖?

**Comment by momoc-ani** [comment]
直接救就行了，分区我改过。最后的办法，耍坏了总要试试。

**Comment by momoc-ani** [comment]
而且现在能刷的固件，基本不会动你的uboot。

**Comment by momoc-ani** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/31720689/195121163-b1c8a9b4-56e2-4f9d-b9e9-d2a3686e7d9b.png">
重新刷回来了，硬件加速支持的

**Comment by ALILEX-1** [comment]
内网拷贝速度文件时,CPU占用多少呢?

openwrt好像是动了分区,没细看

**Comment by momoc-ani** [comment]
<img width="2084" alt="image" src="https://user-images.githubusercontent.com/31720689/195134342-3912b32f-e68f-4e67-85ef-613e78abaa36.png">
不知道这个问题咋解决，害。
没试
